name: restful_service
description: A new Flutter project.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  clean_framework: ^1.5.0
  equatable: ^2.0.5

dev_dependencies:
  clean_framework_test: ^0.1.0-dev.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true